# 名称
name: 部署文档

# 触发条件：在 push 和 pull 到 main 分支后
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 任务
jobs:
  deploy-gh-pages:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 安装依赖
        run: pnpm install

      - name: 构建文档
        run: hexo deploy
